version: 2.0
jobs:
  add-kong:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker-k8:1.8
        auth:
          username: $DOCKER_USER
          password: $QUAY_TOKEN
    steps:
      - checkout
      - run:
          command: ./kong-k8s-go.sh "sandbox.twdps.io"
      - run:
          command: ./test-kong.sh
  delete-kong:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker-k8:1.8
        auth:
          username: $DOCKER_USER
          password: $QUAY_TOKEN
    steps:
      - checkout
      - run:
          command: ./cleanup "sandbox.twdps.io"

workflows:
  version: 2
  kong:
    jobs:
      - add-kong
      - approve-delete-kong:
         type: approval
      - delete-kong:
         requires:
           - approve-delete-kong
